### PR TITLE
Split core packages

### PR DESCRIPTION
**Pull request by joemphilips**
Right now I am testing C# bindings for rust-lightning (see #74 ),
and I want to pass/receive binary serialized data for P2P messages across ffi boundary.

Rather than re-implementing, I'd better use what I have already done in this repository.
But `DotNetLightning.Core` has too much features that I don't use for binding (e.g. Channel State handling, cryptographic ops.)
So In this PR, I will split the project into two 1. `DotNetLightning.Data` for low level primitives and 2. `DotNetLightning.Core` for other things.

It should not break the build since namespaces and visibility is not affected (I suppose).

### CODE REVIEW

**Comment by knocte** [comment]
@joemphilips do you mind creating a "stable" branch before merging this?

**Comment by joemphilips** [comment]
@knocte what do you mean? "stable" for release channel and "master" for releasing nightly version?

Then I think leaving "master"  for stable release and having "staging" branch sounds better to me.

**Comment by knocte** [comment]
Sorry but I have a very strong opinion on this. 'master' should always reflect the latest work being done on a project, and other branches should be checkpoints that QA can bless independently.

**Comment by knocte** [comment]
(It's how the majority of projects work. This way there's no confusion of where should devs create PRs from, for example. I can give you countless examples of projects working this way.)

**Comment by joemphilips** [comment]
Ok. Do you think we should publish nuget package from both?

**Comment by joemphilips** [comment]
If you have no opinion, I will probably add "-stable-" and "-master-" in the version of  the nuget package and publish both.

**Comment by joemphilips** [comment]
Or maybe stop adding suffix to the version for stable release.

**Comment by knocte** [comment]
> If you have no opinion

Just give me time to reply :P

> Or maybe stop adding suffix to the version for stable release.

Yeah I think this is the way, master would always push versions to nuget that have date and git hash (which are treated by default by nuget as "prereleases", just because of the fact that the contain non-numbers on them), but the stable branch ideally would have just numeric versioning (which would make nuget consider them as releases, not pre-releases).

**Comment by joemphilips** [comment]
Finished stabilizing release process in #84 .
I did not introduce new `stable` branch because I thought it is not necessary. Instead, I just push new tag from local and an github action will create new release and nuget package.

I will merge this in few days if @knocte is ok with it.

**Comment by knocte** [comment]
> I will merge this in few days if @knocte is ok with it.

If you merge #85 before merging this one, I'm happy.

**Comment by joemphilips** [comment]
I changed my mind about this.
I will just leave it as is and use the package as a whole, rather than complicating things.

**Pull request closed without merging**
