### PR TITLE
Fix #41

### LINKED ISSUE #41: Unable to find package ResultUtils. No packages exist with this id in source(s): nuget.org
I suspect I am getting this error in geewallet because I am not using your feed. Would it be possible to publish this package on Nuget? Thanks.

### PR DESCRIPTION
**Pull request by joemphilips**
~This should solve #41~ I'm on the way of searching the best way...

### CODE REVIEW

**Comment by knocte** [comment]
I think this is the wrong approach because it would make a piece of OSS software depend on binary blobs ;-)

**Comment by joemphilips** [comment]
umm yes.. I'm seeking for the right approach now...
I think [this issue](https://github.com/dotnet/cli/issues/3959) is where I have to take a look carefully

**Comment by knocte** [comment]
Oh you mean like I did in c98307465f647257df1438beadb4cabc7db757f2 ?

**Comment by joemphilips** [comment]
Yes, I still don't understand the detail of what the code you introduced in that commit do, but I thought adding `PrivateAssets = "all"` to every references I have will solve the problem.

But I think this is not the best way, because the consumer of this package probably want to use `ResultUtils` too.
(TBH, I don't understand what you have mentioned as a binary blobs.)

**Comment by knocte** [comment]
With binary blobs I meant binaries whose source code we don't have (because at first I thought that ResultUtils came from a private feed which came from a private repo of yours, when I first read Janus' comment).

**Pull request merged**
