### PR TITLE
WIP: Remove native-dependency (non-BouncyCastle) support

### PR DESCRIPTION
**Pull request by knocte**
As agreed on https://github.com/joemphilips/DotNetLightning/issues/98#issuecomment-632501898

### CODE REVIEW

**Comment by knocte** [comment]
@joemphilips can you review? if looks good to you I will squash

**Comment by joemphilips** [comment]
Wait, I'm happy to get rid of `Secp256k1.Net` , but not for `NSec`.
(Sorry to confuse you, I've been forgotten that we had more than one choice for AEAD).

**Comment by knocte** [comment]
What is AEAD?

**Comment by joemphilips** [comment]
https://en.wikipedia.org/wiki/Authenticated_encryption

LN uses ChaCha20 and Poly1305 for transport layer communication.

**Comment by knocte** [comment]
But this is also covered with BouncyCastle right?

**Comment by joemphilips** [comment]
> But this is also covered with BouncyCastle right?

Yes, I still want to leave a choice to use libsodium for transport layer encryption.

**Comment by knocte** [comment]
> Wait, I'm happy to get rid of Secp256k1.Net

You already did this in master branch AFAIU, right? If yes, I guess this can be closed?

**Pull request closed without merging**
