### PR TITLE
Stop using NBitcoin fork

### PR DESCRIPTION
**Pull request by knocte**
NOTE: do not merge yet, somehow tests not passing (https://github.com/knocte/DotNetLightning/runs/228729412), help.

### CODE REVIEW

**Comment by joemphilips** [comment]
I cannot see the test log again. :(

**Comment by knocte** [comment]
I sent you an invite to my fork, maybe this way you can see it?

**Comment by knocte** [comment]
Wait a sec, I can see the log even if I'm logged out, just click here: https://github.com/knocte/DotNetLightning/runs/228729412

**Comment by joemphilips** [comment]
When I use version  `4.1.2.33`  of NBitcoin, (which is the original version of my fork.) . This error does not happen.
So I guess it is a bug in NBitcoin side. (Or at least breaking change of TransactionBuilder's behavior.)

I will try to create a PR for NBitcoin from now on. If you are in a hurry, use the version 4.1.2.33 and ignore tests which rely on https://github.com/MetacoSA/NBitcoin/pull/742

**Comment by joemphilips** [comment]
It worked when I changed the order of the opration of tx builder.
It seems that NBitcoin has become more strict about it.
(This is one reason I'm thinking to create my own version of TransactionBuilder. There are many conventions like this that I have to be aware of when using it.)

anyway. now tests are passing

**Pull request merged**
