### PR TITLE
Core: add LTC network prefixes

### PR DESCRIPTION
**Pull request by aarani**
This commit adds support for creating LTC invocies.

### CODE REVIEW

**Comment by joemphilips** [comment]
You need test

**Comment by aarani** [comment]
> You need test

Added.

**Comment by knocte** [comment]
LGTM

**Comment by joemphilips** [comment]
Code change itself seems good.

I'm wondering if we should remove the dependency to `NBitcoin` and solely rely to `NBitcoin.Altcoins`.
having both as a deps might cause a version mismatch issue when bumping etc...
Do you have any opinion on this?

**Comment by knocte** [comment]
> Do you have any opinion on this?

We tested your suggested approach and it works, so the PR has been updated. Merge? Review? :) Thanks

**Comment by joemphilips** [comment]
OK I will just merge it for now.

**Pull request merged**
