### PR TITLE
Stop publishing Macaroons in non-BouncyCastle build.

### PR DESCRIPTION
**Pull request by joemphilips**
* Since Macaroons test has annoying Bug which only occurs in "windows * non-bouncycastle build"
* See https://github.com/joemphilips/DotNetLightning/issues/153

### CODE REVIEW

**Comment by knocte** [comment]
> Stop publishing Macaroons in BouncyCastle build.

You mean in nonBC build? Because later you say `Since Macaroons test has an annoying bug which only occurs in "windows * non-bouncycastle" build`

**Comment by joemphilips** [comment]
> You mean in nonBC build? Because later you say Since Macaroons test has an annoying bug which only occurs in "windows * non-bouncycastle" build

You're right, fixed.

**Comment by knocte** [comment]
> You're right, fixed.

But you didn't fix the commit message 😅

**Comment by joemphilips** [comment]
> But you didn't fix the commit message

whoops. now fixed. I also squashed commits into one.

**Comment by knocte** [comment]
> we renamed this define to Portability recently

you didn't fix this?

**Comment by joemphilips** [comment]
> you didn't fix this?

I'm not sure what you meant.  [We still use `BouncyCastle` as a compile-time variable name](https://github.com/joemphilips/DotNetLightning/blob/179788a33489746fef7bb3de53050514b74f567f/Directory.Build.props#L18)
And that is not affected by this change.

**Comment by knocte** [comment]
Oops you're right, I didn't remember the more specific details of https://github.com/joemphilips/DotNetLightning/commit/3d06651bda42676b48c0a7cbff3aa656e950593f

**Pull request merged**
