### PR TITLE
Update dependencies, fix NSec path

### PR DESCRIPTION
**Pull request by ysangkok**

### CODE REVIEW

**Comment by knocte** [comment]
What's the motivation for updating NBitcoin?

**Comment by knocte** [comment]
And what's the motivation of adding the new `n` parameter? was that supposed to be in this PR?

**Comment by ysangkok** [comment]
I updated because I was worried the different versions or NBitcoin were
causing problems with serialization, so I thought, why not just update all
of them in all packages. The network parameter was added because the API
changed, and the constructor with the single parameter does not exist any
more.

**Comment by ysangkok** [comment]
@knocte More motivation to update NBitcoin: get https://github.com/MetacoSA/NBitcoin/pull/768 which saves us a JsonConverter.

**Comment by NicolasDorier** [comment]
@knocte the new NBitcoin version has some limited support for Nullable Reference that you may like, also I removed support for some stuff that should never have worked in the first place.

**Pull request merged**
