### PR TITLE
githubActions: add a phase for running tests (and build whole solution)

### PR DESCRIPTION
**Pull request by knocte**

### CODE REVIEW

**Comment by knocte** [comment]
@joemphilips seems some tests are failing?

```
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.CreateValue()
   at Secp256k1Net.Secp256k1.Ecdh(ReadOnlySpan`1 publicKey, ReadOnlySpan`1 privateKey, EcdhHashFunction hashFunction, IntPtr data, Span`1 resultOutput) in /home/runner/work/DotNetLightning/DotNetLightning/src/Secp256k1.Net/Secp256k1.cs:line 579
   at Secp256k1Net.Secp256k1.Ecdh(ReadOnlySpan`1 publicKey, ReadOnlySpan`1 privateKey, EcdhHashFunction hashFunction, IntPtr data, Byte[]& resultOutput) in /home/runner/work/DotNetLightning/DotNetLightning/src/Secp256k1.Net/Secp256k1.cs:line 544
   at Secp256k1Net.Test.Tests.EcdhTestCustomHash() in /home/runner/work/DotNetLightning/DotNetLightning/tests/Secp256k1.Net.Test/Tests.cs:line 78
----- Inner Stack Trace -----

Test Run Failed.

Total tests: 11
     Passed: 8
     Failed: 3
 Total time: 8.0828 Seconds
```

**Comment by joemphilips** [comment]
This is weird. It seems secp256k1 is failing to call ffi.

I cannot see the logs for github actions in this branch. Do you know why? @knocte

**Comment by knocte** [comment]
Maybe because you have your repo configured with CI being Azure instead of GithubActions as default? Anyway you can see the log in my fork: https://github.com/knocte/DotNetLightning/runs/227944692

**Comment by joemphilips** [comment]
I just forgot to specify `--enable-module-ecdh` option when building the Secp256k1. will fix it right now.

**Comment by knocte** [comment]
> There is no need to do anything in azure-pipeline if we could finish everything on github actions

Should I remove the azure yml file in this PR too then?

**Comment by joemphilips** [comment]
Yes. Please @knocte

**Comment by knocte** [comment]
> Yes. Please @knocte

Done. Would we see this green now?

**Comment by joemphilips** [comment]
Yes. It is showing green.
But there is something wrong with this. I haven't fixed anything about Secp256k1. So it should keep failing as before.

Plus, it seems that no check has been run. Are you sure that GithubActions are running? I can not merge this until I get sure about what's going on.

> below is my view for this PR. No checks running

範囲を選択_001

**Comment by joemphilips** [comment]
If this is a GithubAction's issue. I think we should rollback to using azure pipeline. It may be too early to use. @knocte

**Comment by knocte** [comment]
I think this might be because this is the PR that removes AzurePipelines itself. Hopefully after merging, the red X or green tick statuses follow GithubActions instead of AzurePipelines. You could merge and if needed, we can revert later.

**Comment by knocte** [comment]
Another reason might be because I created this PR out of nblockchain's fork instead of my fork, and maybe at the time of the creation of it I hadn't activated Actions on that fork yet.

**Comment by joemphilips** [comment]
I think this might be because this is the PR that removes AzurePipelines itself. Hopefully after merging, the red X or green tick statuses follow GithubActions instead of AzurePipelines. You could merge and if needed, we can revert later.

OK I will try

**Comment by joemphilips** [comment]
Yep. It seems to work fine on #8 .

**Comment by knocte** [comment]
Yay.

Now I think it's better to fix the tests first before I propose the NBitcoin-master PR.

**Comment by joemphilips** [comment]
Give me one day. I want to a build binary for every platform. (Including windows and macos.)

**Comment by joemphilips** [comment]
I mean binary for Secp256k1.

**Comment by knocte** [comment]
Can we leave the windows&macOS binary creation for when we have windows&macOS CI lanes? :)

**Comment by joemphilips** [comment]
OK.

**Pull request merged**
