### PR TITLE
fix bug in ClnClient.SendCommandAsync

### PR DESCRIPTION
**Pull request by joemphilips**

### CODE REVIEW

**Comment by knocte** [comment]
what bug?

**Comment by joemphilips** [comment]
@knocte I forgot to use custom JsonSerializer when serializing the request.
Pretty obvious.

**Comment by knocte** [comment]
> @knocte I forgot to use custom JsonSerializer when serializing the request.

That's not the bug, that's the bugfix :) And you didn't include neither in the commit msg.

**Comment by joemphilips** [comment]
> And you didn't include neither in the commit msg

Ok, I've updated the commit msg.

**Comment by knocte** [comment]
> Ok, I've updated the commit msg.

For the record, the commit msg still explained the bugfix but not the bug :)
What should have been added is what was the consequence of JSON not following default settings? That would be the bug ;)

**Pull request merged**
