### PR TITLE
Core: LN.Channel: Use correct keys and to_self_delay for initial ctx

### PR DESCRIPTION
**Pull request by ysangkok**
I discovered this because the remote couldn't validate the commitment signature we send in funding_created. Tested with Electrum and LND on regtest.

### CODE REVIEW

**Comment by knocte** [comment]
But tests break.

**Comment by ysangkok** [comment]
@joemphilips Do you think the test breakage is because of this PR? It passes locally for me, I think the test might be flaky. Especially because it mentions "timeout".

**Comment by knocte** [comment]
BTW, ctx means commitment transaction? or context? I'd prefer to have less abbreviations :)

**Comment by ysangkok** [comment]
@knocte it depends on ctx :P but noted, will try to use more descriptive variable names.

**Comment by knocte** [comment]
Please rename :) BTW, moving forward, don't propose PRs from the master branch of any fork, otherwise the BC nuget package gets published from an unmerged source.

**Comment by ysangkok** [comment]
All right, addressed your comments and opened new PR from right branch.

**Pull request closed without merging**
