### PR TITLE
DotNetLightning.Core: lower .NETCore version requirement

### PR DESCRIPTION
**Pull request by knocte**
This doesn't require .NETCore 3.0 (which is actually not stable yet).

### CODE REVIEW

**Comment by joemphilips** [comment]
Why this is necessary? I don't see any downside for supporting both.

**Comment by knocte** [comment]
It's a transition commit until I actually convert it to NetStandard.

**Comment by knocte** [comment]
(And anyway you're not using any .NETCore 3.0 features so the lower you can support, the better; as you will have wider target audience; since .NETCore 3.0 apps will be compatible with 2.x.)

**Comment by knocte** [comment]
Superseded by https://github.com/joemphilips/DotNetLightning/pull/11

**Pull request closed without merging**
